//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PneuservisISMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BazarTire
    {
        public int Id { get; set; }
        public string Manufacturer { get; set; }
        public int Size { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public int Customers_id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
