//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PneuservisISMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarFleet
    {
        public string CarIdentityNumber { get; set; }
        public int WinterWheelsSize { get; set; }
        public int SummerWheelSize { get; set; }
        public string CarManufacturer { get; set; }
        public string CarType { get; set; }
        public string PreferedTyreManufacturer { get; set; }
        public Nullable<byte> TreadDepthWinter { get; set; }
        public Nullable<byte> TreadDepthSummer { get; set; }
        public int Customers_id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
