//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PneuservisISMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int id { get; set; }
        public int Customers_id { get; set; }
        public int Employees_id { get; set; }
        public System.DateTime CustomerArrival { get; set; }
        public short GarageNumber { get; set; }
        public Nullable<System.DateTime> CustomerExit { get; set; }
        public Nullable<int> Payment { get; set; }
        public Nullable<bool> VAT { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
