//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PneuservisISMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.BazarTires = new HashSet<BazarTire>();
            this.CarFleets = new HashSet<CarFleet>();
            this.Contracts = new HashSet<Contract>();
            this.Orders = new HashSet<Order>();
            this.StoredWheelsDescriptions = new HashSet<StoredWheelsDescription>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string phone { get; set; }
        public string adress { get; set; }
        public string city { get; set; }
        public int postalCode { get; set; }
    
        public virtual ICollection<BazarTire> BazarTires { get; set; }
        public virtual ICollection<CarFleet> CarFleets { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<StoredWheelsDescription> StoredWheelsDescriptions { get; set; }
    }
}
