//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PneuservisISMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Contracts = new HashSet<Contract>();
            this.EmployeeAttendances = new HashSet<EmployeeAttendance>();
            this.Orders = new HashSet<Order>();
            this.StoredWheelsDescriptions = new HashSet<StoredWheelsDescription>();
            this.StoredWheelsDescriptions1 = new HashSet<StoredWheelsDescription>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public byte Experience { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<StoredWheelsDescription> StoredWheelsDescriptions { get; set; }
        public virtual ICollection<StoredWheelsDescription> StoredWheelsDescriptions1 { get; set; }
    }
}
