//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PneuservisISMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendance
    {
        public int Id { get; set; }
        public System.DateTime Arrival { get; set; }
        public Nullable<System.DateTime> Exit { get; set; }
        public Nullable<decimal> Wage { get; set; }
        public bool Paid { get; set; }
        public int Employees_id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
