//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PneuservisISMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSuplierTiresOKPneu
    {
        public string SuplierTiresOKpneu_EAN { get; set; }
        public int Order_Id { get; set; }
        public int ProductCount { get; set; }
        public decimal PricePerPiece { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual SuplierTiresOKpneu SuplierTiresOKpneu { get; set; }
    }
}
