//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PneuservisISMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderSuplierTiresOKPneus = new HashSet<OrderSuplierTiresOKPneu>();
        }
    
        public int Id { get; set; }
        public int Customers_id { get; set; }
        public int Employees_id { get; set; }
        public System.DateTime DATETIME { get; set; }
        public string status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<OrderSuplierTiresOKPneu> OrderSuplierTiresOKPneus { get; set; }
    }
}
