//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PneuservisISMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHistory
    {
        public int id { get; set; }
        public decimal oldPrice { get; set; }
        public System.DateTime DATE { get; set; }
        public string SuplierTiresOKpneu_EAN { get; set; }
    
        public virtual SuplierTiresOKpneu SuplierTiresOKpneu { get; set; }
    }
}
