//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PneuservisISMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoredWheelsDescription
    {
        public int id { get; set; }
        public string Tiremanufacturer { get; set; }
        public string DiscDescription { get; set; }
        public string TireDecription { get; set; }
        public System.DateTime StoreDate { get; set; }
        public Nullable<System.DateTime> UnstoreDate { get; set; }
        public int Customers_id { get; set; }
        public int Employees_id_Store { get; set; }
        public Nullable<int> Employees_id_Unstore { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
