//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PneuservisISMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuplierTiresOKpneu
    {
        public SuplierTiresOKpneu()
        {
            this.PriceHistories = new HashSet<PriceHistory>();
            this.OrderSuplierTiresOKPneus = new HashSet<OrderSuplierTiresOKPneu>();
        }
    
        public string EAN { get; set; }
        public string Manufacturer { get; set; }
        public int Size { get; set; }
        public int ExternalStore { get; set; }
        public string code { get; set; }
        public int OnStore { get; set; }
        public decimal Price { get; set; }
        public string Name { get; set; }
        public string season { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<PriceHistory> PriceHistories { get; set; }
        public virtual ICollection<OrderSuplierTiresOKPneu> OrderSuplierTiresOKPneus { get; set; }
    }
}
